spring:
  application:
    name: productor
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8090
      eager: true

server:
  port: 8001


